In [1]:
import numpy as np

In [2]:
np.array([2,3,4,7,8,9,1,2,3,34,4,5,6,7,4,1])

array([ 2,  3,  4,  7,  8,  9,  1,  2,  3, 34,  4,  5,  6,  7,  4,  1])

In [3]:
np.array([2,3,4,7,8,9,1,2,3,34,4,5,6,7,4,1,10.56])

array([ 2.  ,  3.  ,  4.  ,  7.  ,  8.  ,  9.  ,  1.  ,  2.  ,  3.  ,
       34.  ,  4.  ,  5.  ,  6.  ,  7.  ,  4.  ,  1.  , 10.56])

In [4]:
np.array([[4,5,3,6,7,3],[5,6,4,7,8,34],[3,2,4,5,6,7]])

array([[ 4,  5,  3,  6,  7,  3],
       [ 5,  6,  4,  7,  8, 34],
       [ 3,  2,  4,  5,  6,  7]])

In [5]:
x = np.array([[4,5,3,6,7,3],[5,6,4,7,8,34],[3,2,4,5,6,7]])

In [6]:
x

array([[ 4,  5,  3,  6,  7,  3],
       [ 5,  6,  4,  7,  8, 34],
       [ 3,  2,  4,  5,  6,  7]])

In [7]:
x.shape

(3, 6)

In [8]:
x.reshape(6,3)

array([[ 4,  5,  3],
       [ 6,  7,  3],
       [ 5,  6,  4],
       [ 7,  8, 34],
       [ 3,  2,  4],
       [ 5,  6,  7]])

In [9]:
x.reshape(-1,9)

array([[ 4,  5,  3,  6,  7,  3,  5,  6,  4],
       [ 7,  8, 34,  3,  2,  4,  5,  6,  7]])

In [11]:
x.reshape(3,-1)

array([[ 4,  5,  3,  6,  7,  3],
       [ 5,  6,  4,  7,  8, 34],
       [ 3,  2,  4,  5,  6,  7]])

In [13]:
x[0]

array([4, 5, 3, 6, 7, 3])

In [14]:
x[2]

array([3, 2, 4, 5, 6, 7])

In [15]:
x[0][0]

4

In [16]:
x[0:3]

array([[ 4,  5,  3,  6,  7,  3],
       [ 5,  6,  4,  7,  8, 34],
       [ 3,  2,  4,  5,  6,  7]])

In [17]:
x[:]

array([[ 4,  5,  3,  6,  7,  3],
       [ 5,  6,  4,  7,  8, 34],
       [ 3,  2,  4,  5,  6,  7]])

In [18]:
x[:,0]

array([4, 5, 3])

In [19]:
x[:,3]

array([6, 7, 5])

In [20]:
x[0:2,0:2]

array([[4, 5],
       [5, 6]])

In [23]:
np.random.random()

0.8282797758226489

In [24]:
np.random.random(4)

array([0.53590131, 0.25713351, 0.13567314, 0.88537379])

In [25]:
np.random.random((4,4))

array([[0.62429176, 0.39257845, 0.46869862, 0.61865559],
       [0.10165344, 0.43652718, 0.86345402, 0.959593  ],
       [0.76607352, 0.77133324, 0.60177933, 0.48040767],
       [0.90802944, 0.26653635, 0.68338441, 0.06765061]])

In [27]:
np.random.randint(1,10)

6

In [28]:
np.random.randint(1,10,5)

array([8, 8, 2, 6, 9])

In [29]:
np.random.randint(1,10,(5,5))

array([[7, 9, 5, 4, 7],
       [9, 4, 5, 6, 5],
       [9, 5, 6, 5, 9],
       [1, 4, 8, 8, 2],
       [2, 8, 1, 9, 3]])

In [30]:
y = np.random.randint(1,10,(5,5))

In [31]:
y.shape

(5, 5)

In [34]:
y.flatten('F')

array([6, 7, 3, 6, 8, 1, 9, 1, 8, 3, 7, 5, 2, 6, 7, 4, 7, 9, 5, 2, 1, 5,
       2, 5, 5])

In [33]:
y

array([[6, 1, 7, 4, 1],
       [7, 9, 5, 7, 5],
       [3, 1, 2, 9, 2],
       [6, 8, 6, 5, 5],
       [8, 3, 7, 2, 5]])